### ISSUE TITLE
Create step-by-step tutorial for manager

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#102]

**Comment by websquared** [comment]
@Alinlish Please test by creating a new account (subdomain)

**Comment by Alinlish** [comment]
The step no 5. is "Enable payments" [Link](https://www.screencast.com/t/ChlkMup2oi), and when I click on "Connect with Stripe" an error page is displayed with JSON format [Link](https://www.screencast.com/t/rW3bNBNbnGf). In this case, cannot go on step 6.

**Comment by websquared** [comment]
Should be fixed now

**Comment by Alinlish** [comment]
That part is fixed, but after completing the billing details, the user is logged out, and he is not able to log in again (message "Please register or login first" is displayed) [Link](https://www.screencast.com/t/ehuMqUk37U)
