### ISSUE TITLE
Uploading video in long time

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#11]
It's taking a long time to upload a small mp4 video. Uploading any video is always loading [Link](https://www.screencast.com/t/fxOh279Juefg)

**Comment by websquared** [comment]
I think video is actually uploaded but not showing in preview section and not changing status
@kurumbus please check

**Comment by kurumbus** [comment]
I've changed status, tried to make ui more understandable. In the future I'll try to find if we can speed up upload.
