### ISSUE TITLE
Chat tab on webinar doesn't work anymore

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#114]
(Might be something related to my UI changes - sorry)
Please check and test other tabs as well

**Comment by kurumbus** [comment]
@websquared Will fix this one today.

**Comment by kurumbus** [comment]
nah, as a matter of fact seems like working

**Comment by kurumbus** [comment]
@Alinlish Could you check if the webinar tabs are working? I checked myself, but perhaps you'll notice something.

**Comment by Alinlish** [comment]
@kurumbus The tabs are working good, including chat feature. But I noticed small issues, presented below:
- The message that student entered is displayed in some cases from System Message [Link](https://www.screencast.com/t/xLOxPeJh0wc) and in other cases from Admin [Link](https://www.screencast.com/t/boxpdTb7Vl)
- For student on polls, the message "No active polls yet" is not closing when clicking on x [Link](https://www.screencast.com/t/23J9XWsaRi)
- On resources, the message that no file is uploaded is displayed outside of window [Link](https://www.screencast.com/t/WPdTW4RXF0A)

**Comment by kurumbus** [comment]
- [ ] The message that student entered is displayed in some cases from System Message Link and in other cases from Admin Link

- [ ] For student on polls, the message "No active polls yet" is not closing when clicking on x Link

- [ ] On resources, the message that no file is uploaded is displayed outside of window Link
