### ISSUE TITLE
Error after adding one text content

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#12]
For one cours, if a text content was added, an error page was displayed, and the account on website was not accesible anymore. The account is jeleu1-testing1.learnformula.space [Link](https://www.screencast.com/t/1t8akyIeIL)

**Comment by websquared** [comment]
@Alinlish Strange - I don't see this account "jeleu1-testing1" in our database at all. Could you provide steps to reproduce this issue?

**Comment by Alinlish** [comment]
Steps to reproduce the issue:
1. Open website
2. Register as teacher
3. Create a sub-domain and log in 
4. Create a new course
5. Go to Content and add new text

I just tested and it's not reproducing anymore. I will check also when making other tests.

**Comment by Alinlish** [comment]
@websquared I don't have enough rights to change labels on issues, I can only see them.

**Comment by websquared** [comment]
OK, feel free to close this issue if it works now

**Comment by Alinlish** [comment]
It's not reproducing anymore.
