### ISSUE TITLE
Split landing page templates into categories

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#120]

**Comment by kurumbus** [comment]
@Alinlish Could you test this one? So the deal is: the task was to separate templates into categories and allow user to filter them, that I did.

![Uploading Screenshot 2018-08-20 13.44.52.png…]()

@websquared Are you sure about categories though? Some of them are OK, but we have, for example, "lead generation", and they are all for lead-generation, I guess.
That's just for your information though, I don't think it's that much important.

**Comment by Alinlish** [comment]
@kurumbus Templates are splitted in categories and the filter for categories is working good.
