### ISSUE TITLE
Change landing edit page 

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#121]
Split page into tabs:
- Settings
- Email
- Menu
- Export

Add anything else if needed

**Comment by kurumbus** [comment]
@websquared 
sorry, I forgot what's "export" supposed to do? Did we discuss it?

**Comment by websquared** [comment]
It's marketing automation integration - Mailchimp or Sendgrid

**Comment by websquared** [comment]
Let's call them:
- Settings
- Leads email
- Site menu
- Leads export

**Comment by kurumbus** [comment]
Should I hide this new menu for instructor and manager? I have space for it but perhaps I have a large screen.

![screenshot 2018-08-20 12 51 46](https://user-images.githubusercontent.com/13556916/44333684-1fcd3700-a4a2-11e8-9b59-cf3376cfac8f.png)

**Comment by kurumbus** [comment]
@websquared Should I hide this new menu for instructor and manager? I have space for it but perhaps I have a large screen.

and one more question: should I allow to edit color of call-to-action buttons, and if so, what colors should they choose from? would it be enough to have like 6-8 main ones? (red green blue black etc)

**Comment by websquared** [comment]
Maybe we can combine search and select category in one field like this:
![image](https://user-images.githubusercontent.com/1173105/44349824-e7ab0180-a46b-11e8-9f97-955156c54bb7.png)
https://semantic-ui.com/elements/input.html#action

**Comment by websquared** [comment]
Leave menu with me for now
