### ISSUE TITLE
Back after adding content

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#14]
After adding content for a course (example text or quiz), it would be good to go back on the Content page (or when clicking on Save, or add a new button called Back). [Link](https://www.screencast.com/t/L1eIbTa3u2hZ)

**Comment by Alinlish** [comment]
I just noticed there is a button "Return to course", but it's not very obvious. It hink it's better to place it next to Save.

**Comment by websquared** [comment]
@kurumbus For all the activities except those required to enter addition information after creation (quiz and meeting), let's redirect back to course.
