### ISSUE TITLE
Add date fields for dates

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#15]
When there are dates on application (example Webinar date), it's good to have date fields (where the user can select days, months and years) [Link](https://www.screencast.com/t/BG4pdznS)

**Comment by websquared** [comment]
@Alinlish It already should be this way - if you click on that field it should display a celndar to select date and time. Let me know if it doesn't work for you.

**Comment by Alinlish** [comment]
@websquared Nothing happens when I click on field, not calendar is displayed.

**Comment by websquared** [comment]
Should be fixed now

**Comment by Alinlish** [comment]
It's fixed for courses that have type "Webinar", not for "Live event" courses [Link](https://www.screencast.com/t/45hV0e9lW)
