### ISSUE TITLE
Date and time

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#16]
On date fields, remove time when it is not needed. And when it is needed, it's good to have another fields called time or something similar [Link](https://www.screencast.com/t/Y4qxynlA6fM)

**Comment by websquared** [comment]
@kurumbus Let's keep date and time in one field but display default/entered date in this format: "Sep 4, 1986 8:30 PM" ("lll" if you use momentjs https://momentjs.com/docs/#/displaying/)

**Comment by kurumbus** [comment]
date display should change in quickfix branch
