### ISSUE TITLE
Workflow for course adding

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#19]
When adding a new course, I propose to create a workflow for tabs, in the following way: on tab Settings, when clicking on Save, the tab Landing page is opened, and after clicking Save on Landing page, the next tab is opened, and so on. Or this workflow can be implemented by changing the buttons Save to Next, which include also the saving of data on tabs [Link](https://www.screencast.com/t/lDRbl7qes)

**Comment by websquared** [comment]
@Alinlish Please test it again

**Comment by Alinlish** [comment]
When clicking Save on Settings tab, the second tab is not selected. It's the same like before

**Comment by websquared** [comment]
@Alinlish It will only work if current tab was not marked as completed before saving but became completed after. I other words only if you creating new course, not when you editing it.
You also need to make sure that you actually completed current tab to be redirected to the next one.

**Comment by Alinlish** [comment]
The behavior is like before: I created a new course, on landing page I complete all field, and when I clicked on Submit, the previos tab (Settings) was displayed, not the next tab.

**Comment by websquared** [comment]
Could you take a screencast? It works fine for me.

**Comment by Alinlish** [comment]
I made a video to should that Settings page is opened after Landing page [Video](https://www.screencast.com/t/DFZeXzag)

**Comment by websquared** [comment]
In this case you already had "Landing page" completed.
See my comment https://github.com/websquared/lfc/issues/19#issuecomment-401951504
