### ISSUE TITLE
Clicking on Report abuse

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#20]
Nothing happens when clicking on Report abuse [Link](https://www.screencast.com/t/6e5khv4r)

**Comment by websquared** [comment]
@kurumbus Let's create a page similar to this one with Type and Message fields:
![2018-07-02_15-24-20](https://user-images.githubusercontent.com/1173105/42182389-0e65118e-7e0c-11e8-93ec-dc04547e43d6.png)

You can use the same template/functionality as "Contact Us" page (currently hidden): Route::get('contact-us', 'PageController@contactUs');
