### ISSUE TITLE
The same course recommended

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#21]
When one course is opened, under the sections called "Students Also Bought These Courses", the same course is displayed. In a normal way, other similar courses should be recommended, not the same course [Link](https://www.screencast.com/t/pZq7aYBy)

**Comment by websquared** [comment]
@kurumbus right now we just display "most popular courses" there. We need to generate another list instead that actually means "Students Also Bought These Courses". We might need a new DB table for this and new cron. Let me know your thoughts on how to do that.

**Comment by kurumbus** [comment]
As a matter of fact, I'm positive this won't cause any performance problems any time soon. Even without caching it wouldn't be noticeable until we had about half a million (I think) course enrollments. And I still added caching the partial with recommendations just in case (to make it even faster). So it will hit database like once a day and even then nothing particularly heavy.

I submitted a PR where all this is working, please take a look.
