### ISSUE TITLE
Trainer is added by default

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#22]
When a new course is created, the sentence "Presented by Dr. Ardella Kirlin Sr. " is added. It's not clear from where this trainer is added, but it would be good to be selected when creating the course [Link](https://www.screencast.com/t/eboxbH0i)

**Comment by websquared** [comment]
@kurumbus Looks like it's adding another instructor when creating a course
We need to fix that and also let's create a new tab "Instructors" on course editing navigation:
![2018-07-02_15-34-00](https://user-images.githubusercontent.com/1173105/42182773-60a66d66-7e0d-11e8-9328-9d63f3c10cc9.png)

On that page course creator (main instructor) can add additional instructors to course (they need to be already registered users and have instructor role on that account).

**Comment by kurumbus** [comment]
@websquared there was actually a bug in eloquent relations.

Anyway, fixed and created a tab, please take a look https://drive.google.com/file/d/1QrQ7uRyPcbL8_1i-XUGhNnzvdg7BkNdL/view
