### ISSUE TITLE
Preview course - select an answer

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#26]
On preview a course, when selecting any answer for a quiz, the error message "Please select at least one answer you think is correct" is always displayed. The answer is not taken into consideration, like nothing is selected [Link](https://www.screencast.com/t/iNCIuYI4L8Af)

**Comment by kurumbus** [comment]
@Alinlish I'm sorry, I couldn't reproduce this one. I get this message only when no answers are selected

**Comment by Alinlish** [comment]
I got this message each time I selected one answer for a question. Just preview a question and try to answer. I made a video to show you [Video](https://www.screencast.com/t/b1XylLKm)

**Comment by Alinlish** [comment]
Steps to reproduce:

1. Log in as instructor (email instructor@ex...)
2. Go to My Learning from upper right side
3. Select course "test_question"
4. Select quiz from list
5. Click Start Quiz
6. Select any option and click on Answer

Actual result: one answer is accepted
Expected result: The message "Please select at least one answer you think is correct" is always displayed, no matter what answer is selected.

**Comment by kurumbus** [comment]
Finally I can reproduce it, it's present in firefox only (as I see it). Will get to fixing.
