### ISSUE TITLE
Error at Contact us

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#31]
When seding one message at Contact us [Link](https://www.screencast.com/t/SNsrj9ru), an error page is displayed [Link](https://www.screencast.com/t/iBwAH9GJ0J4T)

**Comment by websquared** [comment]
@Alinlish We actually need to hide this page completely. Where did you see a link to this page?

**Comment by Alinlish** [comment]
@websquared I accessed this page by clicking on "Contact Us" link from footer. But in this moment, the issue described on this ticket is not reproduced anymore.
