### ISSUE TITLE
Reload preview screen after video upload

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#41]
_From @websquared on June 30, 2018 15:58_

Right now it's just grey screen after upload - can we reload this screen with Vue after upload?

![2018-06-30_11-54-26](https://user-images.githubusercontent.com/1173105/42126863-796b8a96-7c5c-11e8-8c43-185e27b012c9.png)

_Copied from original issue: websquared/learnformula-cloud#246_

**Comment by kurumbus** [comment]
@websquared  The problem was that vimeo processes video for quite some time and even if we refresh immedietaly we won't even see black "Video is being processed message". 

But since we now redirect to course page after saving, I guess it is irrelevant.
