### ISSUE TITLE
Remove Name field from video upload page

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#42]
_From @websquared on June 29, 2018 13:36_

- Let's remove this field from video creation page - instead let's detect name from file (convert _ and - to spaces)
- But let's show name field on video editing page - to adjust name if needed

_Copied from original issue: websquared/learnformula-cloud#242_

**Comment by kurumbus** [comment]
@websquared it would be detected automatically, please check this out:
https://drive.google.com/file/d/1c6HY3yZwUd8Zd_-mHn41oQ1ZfafesHmR/view

**Comment by websquared** [comment]
Good. Can we just reorder fields to have upload on top?
And also remove extension from name?
Would it also convert _ or - to spaces?

**Comment by kurumbus** [comment]
Ok. 
Now it removes extension and then converts other .-_ to spaces

![online courses acme inc 3](https://user-images.githubusercontent.com/13556916/42393785-5101d5f2-8160-11e8-8d11-216c62b68531.png)

**Comment by websquared** [comment]
Are you going to do a new PR?
I'm preparing production for final release now before marketing

**Comment by kurumbus** [comment]
@websquared I did create one
