### ISSUE TITLE
Polling v2

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#43]
_From @kurumbus on June 25, 2018 12:5_

Important:

- [x] Use pusher or echo or something to live-monitor polling and resources instead of calling api every now and then.

Less important:

- [x] It's kind of one poll per webinar at the moment. Well, an instructor can refresh the page and create a second one but the first one will be unavailable then to students. (it's more of the coding issue than purposeful design)

Can be moved to other issue for TODO

- [x] Students now see results of the voting. I think this should be up to the instructor.

Let's leave this in one Webinar.vue file for now

- [x] transfer polling to a separate component (perhaps it won't be reusable, but otherwise Webinar.vue will be very hard to refactor). But won't do it without your approval.

@websquared is it OK for an issue?

_Copied from original issue: websquared/learnformula-cloud#231_

**Comment by websquared** [comment]
I've set some priorities for these tasks. Please see issue description.

**Comment by websquared** [comment]
_From @kurumbus on June 27, 2018 9:2_

@websquared understood

**Comment by websquared** [comment]
Webinars is one of the main features that we advertise, so let's make it perfect. Adding it to NOW milestone

**Comment by kurumbus** [comment]
@websquared Will turn to this now.

**Comment by Alinlish** [comment]
My Comments (you already specified the refresh issue):
1. It would be good at beginning when submitting the poll, to show full grey area, without short green at beginning [Link](https://www.screencast.com/t/HfvGej5QI6)
2. When one stuedent has selected one option, the instructor can see 100% as message, but not with green on area [Link1](https://www.screencast.com/t/d8GPEryZ3) or other example [Link2](https://www.screencast.com/t/sIQ9q5Vfj)
3. If the option "Students can see results" is not selected [Link](https://www.screencast.com/t/WLR30WlW7Wg), it's better to remove the poll from student's page, not to keep it empty [Link](https://www.screencast.com/t/deVVMBkECFHC)
4. If adding a new poll with only one option, and then click on Save, the Save or Submit buttons are removed [Link](https://www.screencast.com/t/BFMgTTPpHm)
5. If at one option, a long text is added, the text is not displayed correctly as instructor [Link](https://www.screencast.com/t/lbB4g6Mc) or as student [Link](https://www.screencast.com/t/Bw6Pf4sKVDs). Also, the instructor cannot click End Poll

**Comment by websquared** [comment]
@kurumbus @Alinlish 
I would actually like to change webinar page UI completely in future - see #98

**Comment by kurumbus** [comment]
@websquared Looks cool, right. And "questions" is a useful feature
But we can do something like that.

Should we close this one then now?

**Comment by websquared** [comment]
yes, closing this one
