### ISSUE TITLE
Reschedule notifications if date changes

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#47]
_From @kurumbus on June 20, 2018 8:9_

If webinar changes date:

- [x] delete old scheduled notifications

- [x] dchedule new ones

If a new webinar is added

- [x] schedule notifications for active course users

If meeting is recheduled

- [x] See that notifications are updated accordingly

_Copied from original issue: websquared/learnformula-cloud#215_

**Comment by kurumbus** [comment]
Changed implementation altogether
