### ISSUE TITLE
EDIT COURSE - LANDING PAGE

### ISSUE THREAD

**Issue by MarionneLourdes** [websquared/lfc#5]
![image](https://user-images.githubusercontent.com/40473732/42056524-0dfb4d74-7b4d-11e8-81f6-38712b26d07d.png)

ADDING A COURSE: After filling up "landing page" section and clicking on submit, it shows "Sorry, the page you are looking for could not be found."

**Comment by kurumbus** [comment]
I retested it and there is no bug, so I think we can close it at least for now.
