### ISSUE TITLE
Add sendgrid to marketing automation

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#50]
_From @kurumbus on June 10, 2018 13:11_

Reference: https://sendgrid.com/docs/API_Reference/index.html

_Copied from original issue: websquared/learnformula-cloud#179_

**Comment by websquared** [comment]
@kurumbus Don't we have it implemented already on landing pages?

**Comment by kurumbus** [comment]
@websquared only MailChimp yet, will turn to adding sendgrid now
