### ISSUE TITLE
Better LandingPage

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#52]
_From @kurumbus on June 7, 2018 21:57_

- [x] Cool html5 screenshots to display in landing page list
- [ ] Add editing of images
- [ ] Show and Hide blocks of text or separate ids
- [ ] Add all 14 templates
- [ ] (?) Make homepage editable as well

_Copied from original issue: websquared/learnformula-cloud#173_

**Comment by websquared** [comment]
@kurumbus Landing pages are very important to start promoting this product - so I marked this as Urgent. 
Let's also add all the 14 templates created by Dmitrii.

I'm also thinking to make homepage in similar way - with visual in-place editing instead of current "title" and "subtitle" fields. Can we do that?

**Comment by kurumbus** [comment]
@websquared Ok, I'll get to adding templates.

About homepage. I'm certain we can. I guess you just tell me what of existing templates I could transform (they are for gathering email, but I guess I can just substitute a few blocks here and there and add course grid). We have the same header and footer for landing pages anyways.

So this would take some time, but I wouldn't even say that it's a lot of time.

**Comment by kurumbus** [comment]
- [ ] carelife
- [ ] helptech
- [ ] newcity
- [ ] thanks-10blokks

**Comment by kurumbus** [comment]
@websquared 
Ok,
Since we're in production now, I'll be including new template data in migrations not, in seeder, right?

**Comment by kurumbus** [comment]
@websquared by the way, you say 14 templates, but i certainly don't see 14. I found 5 templates in master branch (+1 thank you), 5 more files in feature/155-template-landings branch (one of which is also thank you)

are there somewhere else?

**Comment by websquared** [comment]
OK, let me check with other Dmitriy about other templates
Yes, we need to do that with migrations from now on

**Comment by kurumbus** [comment]
Added 7 new ones, 9 total yet
