### ISSUE TITLE
Add users on meeting

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#54]
When creating a meeting, it's not clear how to add users on meetings invitations [Link](https://www.screencast.com/t/CtksP78lwhjy)

**Comment by websquared** [comment]
@Alinlish could you explain what's not clear? Do you have any suggestions?

**Comment by websquared** [comment]
@Alinlish Instructor can send meeting invitations to students of this course - it doesn't make sense to send them to other instructors.
Preview mode is actually to preview how course looks for student, usually instructor don't even need to open it.
