### ISSUE TITLE
Preview one video from editing

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#57]
When previewing on video from edit mode of a course [Link](https://www.screencast.com/t/xgDLnhKy), the video cannot be previewed and one error page is displayed [Link](https://www.screencast.com/t/HVCBwhec3S)

**Comment by websquared** [comment]
Did you actually upload a video? Could you try again?

**Comment by Alinlish** [comment]
Yes, I uploaded a video. It's not possible to save a video field without a video file uploaded. The idea is that the same video can be saved twice when clicking on Upload and Save, and the second video does not have a preview. I just checked, this issue is still present.

**Comment by kurumbus** [comment]
Should be working now (after fixing yesterday's bugs)
