### ISSUE TITLE
No finish button on course

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#65]
When previewing or opening one course, and going on pages with Next and Previous buttons, at the end it would be good to have a Finish button, to close the course [Link](https://www.screencast.com/t/O7L5xZfhLnlH)

**Comment by kurumbus** [comment]
@websquared Can do that

**Comment by kurumbus** [comment]
@websquared 
so the way I did it is. If last activity and course completed:
![online courses acme inc 5](https://user-images.githubusercontent.com/13556916/42526955-f7017454-847f-11e8-9bc9-e2cc39d3d2a7.png)


if last activity but course not completed:
![online courses acme inc 6](https://user-images.githubusercontent.com/13556916/42526986-108f34c4-8480-11e8-93d1-447af617066f.png)
