### ISSUE TITLE
Add all categories for courses

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#66]
Proposal: for the categories option related to courses, add the option to view all courses [Link](https://www.screencast.com/t/8x1VI1W9gdW)

**Comment by kurumbus** [comment]
@websquared I also think it might be a good idea. Can we do this way?

![2018-07-10](https://user-images.githubusercontent.com/13556916/42525581-30f62bfe-847c-11e8-9334-5c8dab2f7c6b.png)
