### ISSUE TITLE
Default image for courses

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#69]
For courses that don't have a course uploaded, I propose to add a default image to be displayed, because in this moment, the courses have a picture that looks like a broken image [Link](https://www.screencast.com/t/DNp3RaGXBTAf)

**Comment by kurumbus** [comment]
@websquared i also have this problem locally, but it's actually because I can't access some files (or they do not exist perhaps)
For example I have 403 on this link:
https://learnformula-cloud.s3.amazonaws.com/images/courses/sample/9.jpg

**Comment by websquared** [comment]
@Alinlish this should be fixed now

**Comment by Alinlish** [comment]
Yes, it's fixed.
