### ISSUE TITLE
Text or article

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#72]
On a course, when adding content, the button is called "Add Text" [Link](https://www.screencast.com/t/OVw5cUxrU) and on the opened page, the title is "Article" [Link](https://www.screencast.com/t/R7V8iSjvWX)

**Comment by kurumbus** [comment]
I guess there was only one place where it was called 'text' instead of 'Article', but if you @Alinlish by chance see it somewhere, please let me know.
