### ISSUE TITLE
The same Save button for image and video

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#73]
When adding a course, on tab Landing Page, I propose for a better usability, to have only one Save button (the one from bottom), and with that button to save both image and video [Link](https://www.screencast.com/t/g043fQMyQe)

**Comment by kurumbus** [comment]
@websquared i think i could implement a small intercept:
if user clicks green save button (submitting form), js will first save course image and only then get back to submitting form. What would you say?

**Comment by websquared** [comment]
@kurumbus Yes, I like it - let's do that
