### ISSUE TITLE
Register page displayed after log in

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#76]
When opening the website, then go to Log-in, completing the email "instructor@example.com" with correct password, and clicking on Login, the register page is displayed. Normally the user should be logged in application directly [Link](https://www.screencast.com/t/IEex0Raec)

**Comment by kurumbus** [comment]
@websquared I think it's related with https certificate, so it's not directly related to code itself.
(can be wrong of course)

**Comment by websquared** [comment]
@Alinlish Do you login initially on main domain or subdomain? Please indicate this in steps to reproduce. I just tried and it works fine for me - except HTTPS certificate warning - but this is expected on dev site
