### ISSUE TITLE
Nullable old price

### ISSUE THREAD

**Issue by kurumbus** [websquared/lfc#77]
Now we can't set old price to null if course is not discounted and set it to 0, and check if old_price > 0

Now wouldn't it be more logical to set it to null?

**Comment by websquared** [comment]
Based on my experience it's always better have numerical DB fields not nullable - it will create more confusion later in code if we would have both NULL and 0 values.
Nullable should be only set to "string" or "date" DB columns.

**Comment by kurumbus** [comment]
@websquared Closing it then
