### ISSUE TITLE
Long text for selecting a meeting

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#82]
When logged in as instructor, at tab My students, if schedulling a meeting, at select a meeting, a very long text is displayed, which is not helpful in this case [Link](https://www.screencast.com/t/n4ezFkreN)

**Comment by websquared** [comment]
@kurumbus Not a high priority but let's just make this field searchable:
https://semantic-ui.com/modules/dropdown.html#search-selection

**Comment by Alinlish** [comment]
The behavior is exactly like before. Steps to reproduce:
1. Open website and log in with instructor account (instructor@ex...)
2. Click on Instructor Tools from upper right side
3. Select tab My Students
4. For one student, click on Schedule a meeting
5. Select a meeting from drop-down

Expected result: Meetings are displayed on drop-down.
Actual result: a long text is displayed on drop-down [Link](https://www.screencast.com/t/n4ezFkreN)

**Comment by kurumbus** [comment]
@websquared Actually it's embarrassing, but it was a dropdown with more then 500 options i.e. it was displaying all the meetings in the db, not the ones user has access to, not even all meetings in account, just all.

I fixed that and made field searchable too. Although now it searches through like 3-4 fields
