### ISSUE TITLE
Error page when completing date on Price page

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#85]
Steps:
1. Open website and log in with instructor account (instructor@ex...)
2. Go to Instructor tools -> Create a course
3. On price tab, complete all fields, and select a date [Link](https://www.screencast.com/t/9ktAvcWe)
4. Click on Save

Expected result: All fields on Price tab are saved
Actual result: An error page is displayed [Link](https://www.screencast.com/t/CfbTV75ZFq8a)

**Comment by kurumbus** [comment]
Will take that
