### ISSUE TITLE
Error email

### ISSUE THREAD

**Issue by mkatsevman** [websquared/lfc#86]
Set that you don't get error in template for e-mail address entered

https://dog1.learnformula.com/accounts/leads/templates/fitness-ebook
<img width="1177" alt="screen shot 2018-07-10 at 2 17 51 pm" src="https://user-images.githubusercontent.com/40309392/42529308-1e552a84-844c-11e8-8c16-b22074240e9d.png">

**Comment by websquared** [comment]
@kurumbus This happens when you open a template as a manager and try to submit an email in form

**Comment by kurumbus** [comment]
@websquared since it affects only templates this is how I implemented the fix
https://drive.google.com/file/d/1mgOOQ8dqYqa0lp7T5JOFqi99juHZW_88/view
