### ISSUE TITLE
Error for get completion certificate

### ISSUE THREAD

**Issue by Alinlish** [websquared/lfc#89]
Steps:
1. Open website and log in as student (student@ex...)
2. Go to My Learning
3. From My Courses, open a course
4. Click on one item from course
5. Complete all items
6. On last item, click on Next: Get Completion certificate [Link](https://www.screencast.com/t/tpVk3rYwPa)

Expected result: Completion certificate is displayed
Actual result: An error page is displayed [Link](https://www.screencast.com/t/1IJpLpL2Xy)

**Comment by websquared** [comment]
@kurumbus I thought it was fixed - but could you check that certificates are saved in Laravel storage folder, not in parent "temp" folder as it's doing now.

**Comment by kurumbus** [comment]
@websquared it saves them to storage directory, I think the library generating certificate still needs access to the temp directory

![whoops there was an error](https://user-images.githubusercontent.com/13556916/42715505-0a7562de-8700-11e8-93e1-6297244e149d.png)

**Comment by websquared** [comment]
Actually I found this path configured in config/pdf.php - changed "base_path" to "storage_path"

**Comment by websquared** [comment]
@Alinlish please retest

**Comment by Alinlish** [comment]
When performing the steps described in this issue, another error page is displayed [Link](https://www.screencast.com/t/oJH8BsANYK)

**Comment by kurumbus** [comment]
@websquared perhaps I know why that could be
Could you tell me what queue driver we have at learnformula.space ?

If it's sync - the error is because the app doesn't wait an hour to delete certificate file, but deletes it right away. We could remove this deleting file altogether, but I thought those certificates take too much drive space

**Comment by websquared** [comment]
@kurumbus Queue drive is "database" - same as on production. Assigning this to you to investigate

**Comment by kurumbus** [comment]
@Alinlish Should finally work, please take a look

**Comment by Alinlish** [comment]
It's solved.
