### ISSUE TITLE
External Services integration

### ISSUE THREAD

**Issue by kurumbus** [websquared/lfc#91]
I propose several improvements

![online courses acme inc 7](https://user-images.githubusercontent.com/13556916/42731761-bf9f1c14-881c-11e8-9eaf-a7eed04c7b5b.png)

- [x] Testing Connection to external service upon connecting.
- [x] Ability to delete and add new (essentially change provider from  mailchimp to sendgrid and back)

Estimated Time: 1-2 hours (if I don't get stuck on the way).

**Comment by websquared** [comment]
Yes, we should definitely do these improvements. Thanks.

**Comment by kurumbus** [comment]
@Alinlish could you test if it's working please? 

You would need to register at mailchimp and sendgrid and try connecting and disconnecting using API keys they give. If you have any questions, please don't hesitate to ask.

**Comment by Alinlish** [comment]
I tested with 3-4 different API Keys, it's working good, with one exception: I am able to save a SendGrid API Key to MailChimp service [Link1](https://www.screencast.com/t/izQsVX6Fr) [Link2](https://www.screencast.com/t/TQOXBQm0)

**Comment by websquared** [comment]
We might need to do some test API call to validate entered API key in future

**Comment by kurumbus** [comment]
@websquared we do, I use "getLists", it's simple enough.

I the key is incorrect, service is not saved and error thrown

**Comment by kurumbus** [comment]
@websquared the problem was that MailChimp sends false instead of 403 when api key is not too short but incorrect (weird, but that's how I understand their idea).  But now I added this check.
