### ISSUE TITLE
Fix 2 production errors

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#97]
I've installed Laravel Log Viewer, but you need to be an admin to open it.
Please create a new account on production and I'll set an admin role for you.

https://learnformula.com/log-viewer/logs/2018-07-18/error

- [x] htmlspecialchars() expects parameter 1 to be string, array given (View: /var/www/learnformula-cloud/laravel/resources/views/profile/partials/avatar.blade.php)
- [x] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cron_data' in 'where clause' (SQL: select * from `course_users` where `cron_data`->'$."first_date"' = 18/07/2018 or `cron_data`->'$."second_date"' = 18/07/2018)

**Comment by websquared** [comment]
Yes, you have a user for grigory.shein@gmail.com - it's linked to kurumbus.learnformula.com account

**Comment by websquared** [comment]
Strange that it says "Please register or login first" - it should say that password is incorrect

**Comment by kurumbus** [comment]
@websquared 
I can login at https://kurumbus.learnformula.space/ - so it just doesn't redirect (although it does locally on my localhost).

**Comment by kurumbus** [comment]
Btw accidentally noticed first error on my own and fixed here https://github.com/websquared/lfc/issues/100

**Comment by kurumbus** [comment]
@websquared  As for second: we had a column 'cron_data ' in course_users but you removed it quite a while ago, 26th of april.

I actually can't understand where those "first_date" and "second_date" go, are those created_at and updaed_at?

**Comment by websquared** [comment]
Looks like an issue is here: app/Console/Commands/VerifyChargeInstalment.php

This was done by other developer but since then we modified "course_users" table and instead of "cron_data" it has separate columns like "next_run", "last_run", "run_count", "total_runs".

We would need to update this VerifyChargeInstalment file to reflect this

**Comment by kurumbus** [comment]
@websquared yes and few lines later in this file there is a condition
$courseToPay->payment_method == 3
I assume it is "instalment", I remember payment_method used to to be integer some time ago.

**Comment by kurumbus** [comment]
@websquared  please take a look at my pull request. While we should get rid of errror, I'm completely not sure that this is how all of this supposed to work. Would you like me to get deeper? Or does this look right to you?

**Comment by websquared** [comment]
I don't see a pull request yet
