### ISSUE TITLE
Webinar UI v2

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#98]
Examples: https://livestorm.co/features/

**Comment by websquared** [comment]
@kurumbus Let's start working on the similar UI now - because it's one of the most important platform features.

![image](https://user-images.githubusercontent.com/1173105/42968829-706c220a-8b72-11e8-8f5e-44125810b08b.png)

**Comment by kurumbus** [comment]
@websquared Ok this is top priority. I'm afraid to make promises, but I'll do my best to finish by the end of the weekend (day after tomorrow).

**Comment by kurumbus** [comment]
- [X] Full screen container
- [X] Content in tabs
- [ ] member and instruction representation in members and chat (add avatar, subtitle)
- [ ] Use echo "joining" events to monitor presence
- [ ] Add question functionality
- [ ] Necessary service buttons

**Comment by kurumbus** [comment]
@Alinlish Could you take a look at the new interface and share some thoughts

**Comment by Alinlish** [comment]
My comments:
1. On instructor side, student is not added on members list [Link](https://www.screencast.com/t/bOy4GMBhhB9), as it is for student [Link](https://www.screencast.com/t/cZwNiH8qCqO)
2. It would be good at beginning when submitting the poll, to show full grey area, without short green at beginning [Link](https://www.screencast.com/t/oIftqdXp)
3. After voting and refreshing the page, the student can vote again [Link](https://www.screencast.com/t/0Ua8GiMw)
4. After voting again, the green area is not updated for student, for example if the percentage is 50%, the green area is displayed for 100% [Link](https://www.screencast.com/t/oJox2wHw)
5. If a student voted, the percentage is updated for instructor, but not the green area [Link](https://www.screencast.com/t/S5GUE1ifasif)
6. If adding a new poll with only one option, and then click on Save, the Save or Submit buttons are removed [Link](https://www.screencast.com/t/Oh2RoVsNc)
7. If at one option, a long text is added, the text is not displayed correctly as instructor [Link](https://www.screencast.com/t/UYCdU96W) or as student [Link](https://www.screencast.com/t/TmMoRCRnjmhA). Also, the instructor cannot click End Poll
8. Message "You haven't published any polls yet" is displayed also after the instructor posted a poll [Link](https://www.screencast.com/t/K48eByout)
9. Message "You haven't published any polls yet" is displayed also for student, which doesn't make any sense [Link](https://www.screencast.com/t/U779KI7dNE)
10. If the option "Students can see results" is not selected [Link](https://www.screencast.com/t/uvrRcyxUdCO4), it's better to remove the poll from student's page, not to keep it empty [Link](https://www.screencast.com/t/F18o8ebg5)
11. After completing one poll that he cannot see, the student can add poll, which doesn't make sense (only instructor should add poll) [Link](https://www.screencast.com/t/0DoqC49c)
12. Poll is too much on the right edge, it could be good to move it a little bit on left side [Link](https://www.screencast.com/t/pkDdpEVATn)
13. When sending a question on many lines as student [Link](https://www.screencast.com/t/gujZ9GHOW), the question is sent on only one line [Link](https://www.screencast.com/t/r3VgNFBIvW4)
14. When adding one resource as instructor, no file type is accepted as resource. It would be good to say what files types are expected [Link](https://www.screencast.com/t/Y6u4tmBcY)
15. One error is displayed when trying to perform a streaming [Link](https://www.screencast.com/t/XLe3qFmVbxen)

**Comment by kurumbus** [comment]
@Alinlish thank you!

**Comment by websquared** [comment]
@kurumbus please let me know if you need any help with it. I would like to deploy new UI asap and continue sales and marketing.

**Comment by kurumbus** [comment]
@websquared I think that point 15  is related to folder permissions, so it requires server access. 
Otherwise seems doable.

**Comment by kurumbus** [comment]
- [X] 6 If adding a new poll with only one option, and then click on Save, the Save or Submit buttons are removed

- [X] 8 Message "You haven't published any polls yet" is displayed also after the instructor posted a poll 

- [X] 9 Message "You haven't published any polls yet" is displayed also for student, which doesn't make any sense

**Comment by kurumbus** [comment]
- [X] 10 If the option "Students can see results" is not selected Link, it's better to remove the poll from student's page, not to keep it empty 
- [X] 11 After completing one poll that he cannot see, the student can add poll, which doesn't make sense (only instructor should add poll)

**Comment by kurumbus** [comment]
- [X] 12 Poll is too much on the right edge, it could be good to move it a little bit on left side
- [X] 13 When sending a question on many lines as student Link, the question is sent on only one line

**Comment by websquared** [comment]
@Alinlish Could you test this again? I've made some additional UI changes

**Comment by Alinlish** [comment]
I tested again, the points 5, 6, 8, 9, 10, 11, 12 and 13 are solved. The points 2, 3, 4, 7 and 14 are the same. And for points 1 and 15, my comments are:
- one important issue is that the menu items of webinar are not accessible from first time. I have to click for many times in order to see details under one menu item [Video](https://www.screencast.com/t/2A96qREwyL9)
- if the student left the webinar, he is still displayed under participants [Link](https://www.screencast.com/t/wiiFKtmkD)
- cannot click on Start Preview, it is disabled (after performing all steps) [Link](https://www.screencast.com/t/QDm0jkdX)

**Comment by kurumbus** [comment]
- [ ] 1 On instructor side, student is not added on members list Link, as it is for student
- [ ] 2  It would be good at beginning when submitting the poll, to show full grey area, without short green at the beginning 
- [ ] 3 After voting and refreshing the page, the student can vote again 
- [ ] 4 After voting again, the green area is not updated for student, for example if the percentage is 50%, the green area is displayed for 100% 
- [ ] 7 If at one option, a long text is added, the text is not displayed correctly as instructor Link or as student Link. Also, the instructor cannot click End Poll 
- [ ] 14 When adding one resource as instructor, no file type is accepted as resource. It would be good to say what files types are expected

**Comment by kurumbus** [comment]
@websquared At the moment any file type can become a resource, we don't limit that (cause I don't know the reason to do so). But should I do it?

**Comment by websquared** [comment]
I think we should limit file types - but again, it's a low priority
Let's allow only these for now: pdf, doc(x), xsl(x), ppt(x), txt and images.
Also let's limit each file to 10Mb for now.

**Comment by kurumbus** [comment]
@Alinlish could you test this one in general? (didn't limit file types yet, will do it in a day or so)

**Comment by Alinlish** [comment]
My comments:
- For 2, the color was changed from green to dark grey. My idea was that at 0% to not have any different color at start (now there is dark grey). For example, if the percentage 0% is not displayed as text under option, the pencentage looks like 10% [Link](https://www.screencast.com/t/Os7cBIUWVcAv)
- The points 1, 3, and 4 are solved.
- The point 7 is improved, but the text is still displayed above "End Poll" button [Link](https://www.screencast.com/t/E15VYbRryP55). Also, I propose to add a sign to show that more text is coming, example (...)
- For 14, you are right, now all field types are accepted.
- For 15, the error message is still displayed sometimes.

**Comment by kurumbus** [comment]
@Alinlish 
- About colour: I agree with you but this is kind of a limitation of a framework. It can be fixed, but with an absolutely unjustifiable amount of spent time.
- About long options: fixed that, limited to 140 symbols. I don't really know how often this would be a problem.
- About error:  it's not really webinar related. 

@websquared I've limited accepted filetypes on form, as you said, but are we getting something from it? This is just front-end validation which doesn't really prevent anything malicious. But is it really necessary to prevent users to upload something little more exotic like rtf, or odf (open document format)? If it's a question of security, would you like me to create a task for the future for something like server-side file check?
Yes, also added 10Mb limit. 

I think we can close this one after PR, it should all work reasonably well.
